# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-30 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0027_auto_20170824_1157'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='codd',
            field=models.CharField(blank=True, max_length=30),
        ),
    ]
