# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-30 12:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0028_profile_codd'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='status',
            field=models.CharField(blank=True, default=b'0', max_length=30),
        ),
    ]
